on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'folders before'
        run: ls

     - uses: actions/checkout@v3

      - name: 'folders after'
        run: ls

